//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCexample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressTablee
    {
        public int ID { get; set; }
        public Nullable<int> accountID { get; set; }
        public string PhoneNumber { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Parish { get; set; }
        public string address { get; set; }
        public string Title { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual registerTable registerTable { get; set; }
    }
}
