//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCexample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.BasketContent = new HashSet<BasketContent>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<byte> StarCount { get; set; }
        public string CommentText { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasketContent> BasketContent { get; set; }
        public virtual Product Product { get; set; }
        public virtual registerTable registerTable { get; set; }
    }
}
