//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCexample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.BasketContent = new HashSet<BasketContent>();
            this.Comment = new HashSet<Comment>();
            this.ProductDetail = new HashSet<ProductDetail>();
            this.Favorite = new HashSet<Favorite>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public Nullable<int> Stock { get; set; }
        public double Price { get; set; }
        public string Image { get; set; }
        public Nullable<double> OutletPrice { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> CategoryLowerTitleID { get; set; }
        public Nullable<int> CategoryLowerID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Outlet { get; set; }
        public Nullable<bool> Popular { get; set; }
        public Nullable<byte> memory { get; set; }
        public string proccesorBrand { get; set; }
        public Nullable<int> battery { get; set; }
        public Nullable<byte> screenSize { get; set; }
        public string screenType { get; set; }
        public string backCameraResulation { get; set; }
        public Nullable<byte> backCameraCount { get; set; }
        public Nullable<bool> backCameraFlas { get; set; }
        public string selfieCameraResulation { get; set; }
        public Nullable<byte> selfieCameraCount { get; set; }
        public Nullable<bool> selfieCameraFlas { get; set; }
        public string color { get; set; }
        public Nullable<byte> RAM { get; set; }
        public string CPU { get; set; }
        public string connectionSpeed { get; set; }
        public Nullable<bool> Bluetooth { get; set; }
        public Nullable<bool> doubleLine { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasketContent> BasketContent { get; set; }
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDetail> ProductDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite> Favorite { get; set; }
    }
}
